version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-only
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://premiumchat:password@db:5432/premiumchat
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=premiumchat
      - POSTGRES_USER=premiumchat
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge